name: match_generator
description: Generator for match extension methods
version: 0.2.0
homepage: https://github.com/mrbech/match

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  match: ^0.2.0
  #match:
  #  path: ../match
  build: ^1.3.0
  source_gen: ^0.9.5
  analyzer: 0.39.14

dev_dependencies:
  pedantic: ^1.9.0
  build_test: any
  build_runner: any
  test: ^1.14.6
