name: match_generator
description: Generator for match extension methods
version: 0.3.1
homepage: https://github.com/mrbech/match

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  match: ^0.3.1
  #match:
  #  path: ../match
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0
  build_test: any
  build_runner: any
  test: ^1.14.6
